# Generated by Django 5.1.6 on 2025-02-17 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('transports', '0001_initial'),
        ('users', '0002_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preffered_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hotel_stars', models.IntegerField(default=0)),
                ('preferred_place_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='places.placecategories')),
                ('preferred_transport_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='transports.transporttypes')),
            ],
        ),
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'query'], name='users_users_user_id_b57a19_idx')],
            },
        ),
    ]
