# Generated by Django 5.1.6 on 2025-02-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
        ('users', '0003_userpreference_usersearch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransportTypes',
            new_name='TransportType',
        ),
    ]
